INSERT INTO `inventory_departamento` VALUES(1, 'CAPITAL');
INSERT INTO `inventory_departamento` VALUES(2, 'CONCEPCION');
INSERT INTO `inventory_departamento` VALUES(3, 'SAN PEDRO');
INSERT INTO `inventory_departamento` VALUES(4, 'CORDILLERA');
INSERT INTO `inventory_departamento` VALUES(5, 'GUAIRÁ');
INSERT INTO `inventory_departamento` VALUES(6, 'CAAGUAZÚ');
INSERT INTO `inventory_departamento` VALUES(7, 'CAAZAPÁ');
INSERT INTO `inventory_departamento` VALUES(8, 'ITAPÚA');
INSERT INTO `inventory_departamento` VALUES(9, 'MISIONES');
INSERT INTO `inventory_departamento` VALUES(10, 'PARAGUARÍ');
INSERT INTO `inventory_departamento` VALUES(11, 'ALTO PARANÁÚ');
INSERT INTO `inventory_departamento` VALUES(12, 'CENTRAL');
INSERT INTO `inventory_departamento` VALUES(13, 'ÑEEMBUCÚ');
INSERT INTO `inventory_departamento` VALUES(14, 'AMAMBAY');
INSERT INTO `inventory_departamento` VALUES(15, 'PRESIDENTE HAYES');
INSERT INTO `inventory_departamento` VALUES(16, 'BOQUERÓN');
INSERT INTO `inventory_departamento` VALUES(17, 'ALTO PARAGUAY');
INSERT INTO `inventory_departamento` VALUES(18, 'CANINDEYÚ');