INSERT INTO `inventory_distrito` (`id`, `descripcion`, `departamento_id`) VALUES (1, 'ASUNCION(CENTRAL)', 1);
INSERT INTO `inventory_distrito` (`id`, `descripcion`, `departamento_id`) VALUES (2, 'CONCEPCION(MUNICIPIO)', 2);
INSERT INTO `inventory_distrito` (`id`, `descripcion`, `departamento_id`) VALUES (3, 'SAN LORENZO', 2);
INSERT INTO `inventory_distrito` (`id`, `descripcion`, `departamento_id`) VALUES (4, 'SAN CARLOS', 2);
INSERT INTO `inventory_distrito` (`id`, `descripcion`, `departamento_id`) VALUES (5, 'BELEN', 2);
INSERT INTO `inventory_distrito` (`id`, `descripcion`, `departamento_id`) VALUES (6, 'LORETO', 2);
INSERT INTO `inventory_distrito` (`id`, `descripcion`, `departamento_id`) VALUES (7, 'HORQUETA', 2);
INSERT INTO `inventory_distrito` (`id`, `descripcion`, `departamento_id`) VALUES (8, 'SAN SALVADOR', 2);
INSERT INTO `inventory_distrito` (`id`, `descripcion`, `departamento_id`) VALUES (9, 'YBY YAU', 2);
INSERT INTO `inventory_distrito` (`id`, `descripcion`, `departamento_id`) VALUES (10, 'SAN PEDRO DE YCUAMANDYYU', 3);
INSERT INTO `inventory_distrito` (`id`, `descripcion`, `departamento_id`) VALUES (11, 'ANTEQUERA', 3);
INSERT INTO `inventory_distrito` (`id`, `descripcion`, `departamento_id`) VALUES (12, 'GRAL. E.AQUINO', 3);
INSERT INTO `inventory_distrito` (`id`, `descripcion`, `departamento_id`) VALUES (13, 'ITACURUBI DEL ROSARIO', 3);
INSERT INTO `inventory_distrito` (`id`, `descripcion`, `departamento_id`) VALUES (14, 'SAN ESTANISLAO (SANTANI)', 3);
INSERT INTO `inventory_distrito` (`id`, `descripcion`, `departamento_id`) VALUES (15, 'LIMA', 3);
INSERT INTO `inventory_distrito` (`id`, `descripcion`, `departamento_id`) VALUES (16, 'NUEVA GERMANIA', 3);
INSERT INTO `inventory_distrito` (`id`, `descripcion`, `departamento_id`) VALUES (17, 'TACUATI', 3);
INSERT INTO `inventory_distrito` (`id`, `descripcion`, `departamento_id`) VALUES (18, 'UNION', 3);
INSERT INTO `inventory_distrito` (`id`, `descripcion`, `departamento_id`) VALUES (19, '25 DE DICIEMBRE', 3);
INSERT INTO `inventory_distrito` (`id`, `descripcion`, `departamento_id`) VALUES (20, 'VILLA DEL ROSARIO', 3);
INSERT INTO `inventory_distrito` (`id`, `descripcion`, `departamento_id`) VALUES (21, 'YATAITY DEL NORTE', 3);
INSERT INTO `inventory_distrito` (`id`, `descripcion`, `departamento_id`) VALUES (22, 'ISIDORO RESQUIN', 3);
INSERT INTO `inventory_distrito` (`id`, `descripcion`, `departamento_id`) VALUES (23, 'CHORE', 3);
INSERT INTO `inventory_distrito` (`id`, `descripcion`, `departamento_id`) VALUES (24, 'SAN PABLO', 3);
INSERT INTO `inventory_distrito` (`id`, `descripcion`, `departamento_id`) VALUES (25, 'SAN JOSE DEL ROSARIO', 3);
INSERT INTO `inventory_distrito` (`id`, `descripcion`, `departamento_id`) VALUES (26, 'CAACUPE', 4);
INSERT INTO `inventory_distrito` (`id`, `descripcion`, `departamento_id`) VALUES (27, 'ALTOS', 4);
INSERT INTO `inventory_distrito` (`id`, `descripcion`, `departamento_id`) VALUES (28, 'ARROYOS Y ESTEROS', 4);
INSERT INTO `inventory_distrito` (`id`, `descripcion`, `departamento_id`) VALUES (29, 'ATYRA', 4);
INSERT INTO `inventory_distrito` (`id`, `descripcion`, `departamento_id`) VALUES (30, 'CARAGUATAY', 4);
INSERT INTO `inventory_distrito` (`id`, `descripcion`, `departamento_id`) VALUES (31, 'EMBOSCADA', 4);
INSERT INTO `inventory_distrito` (`id`, `descripcion`, `departamento_id`) VALUES (32, 'EUSEBIO AYALA', 4);
INSERT INTO `inventory_distrito` (`id`, `descripcion`, `departamento_id`) VALUES (33, 'ISLA PUCU', 4);
INSERT INTO `inventory_distrito` (`id`, `descripcion`, `departamento_id`) VALUES (34, 'ITACURUBI DE LA CORDILLERA', 4);
INSERT INTO `inventory_distrito` (`id`, `descripcion`, `departamento_id`) VALUES (35, 'JUAN DE MENA', 4);
INSERT INTO `inventory_distrito` (`id`, `descripcion`, `departamento_id`) VALUES (36, 'NUEVA COLOMBIA', 4);
INSERT INTO `inventory_distrito` (`id`, `descripcion`, `departamento_id`) VALUES (37, 'PIRIBEBUY', 4);
INSERT INTO `inventory_distrito` (`id`, `descripcion`, `departamento_id`) VALUES (38, '1RO.DE MARZO', 4);
INSERT INTO `inventory_distrito` (`id`, `descripcion`, `departamento_id`) VALUES (39, 'SAN BERNARDINO', 4);
INSERT INTO `inventory_distrito` (`id`, `descripcion`, `departamento_id`) VALUES (40, 'SANTA ELENA', 4);
INSERT INTO `inventory_distrito` (`id`, `descripcion`, `departamento_id`) VALUES (41, 'TOBATI', 4);
INSERT INTO `inventory_distrito` (`id`, `descripcion`, `departamento_id`) VALUES (42, 'VALENZUELA', 4);
INSERT INTO `inventory_distrito` (`id`, `descripcion`, `departamento_id`) VALUES (43, 'LOMA GRANDE', 4);
INSERT INTO `inventory_distrito` (`id`, `descripcion`, `departamento_id`) VALUES (44, 'SAN JOSE OBRERO', 4);
INSERT INTO `inventory_distrito` (`id`, `descripcion`, `departamento_id`) VALUES (45, 'VILLARRICA', 5);
INSERT INTO `inventory_distrito` (`id`, `descripcion`, `departamento_id`) VALUES (46, 'SAN SALVADOR', 5);
INSERT INTO `inventory_distrito` (`id`, `descripcion`, `departamento_id`) VALUES (47, 'BORJA', 5);
INSERT INTO `inventory_distrito` (`id`, `descripcion`, `departamento_id`) VALUES (48, 'INDEPENDENCIA (R.D.MELGAREJO)', 5);
INSERT INTO `inventory_distrito` (`id`, `descripcion`, `departamento_id`) VALUES (49, 'GRAL.EUGENIO A. GARAY', 5);
INSERT INTO `inventory_distrito` (`id`, `descripcion`, `departamento_id`) VALUES (50, 'CNEL. MARTINEZ', 5);
INSERT INTO `inventory_distrito` (`id`, `descripcion`, `departamento_id`) VALUES (51, 'JOSE FASSARDI', 5);
INSERT INTO `inventory_distrito` (`id`, `descripcion`, `departamento_id`) VALUES (52, 'FELIX PEREZ CARDOZO', 5);
INSERT INTO `inventory_distrito` (`id`, `descripcion`, `departamento_id`) VALUES (53, 'MAURICIO JOSE TROCHE', 5);
INSERT INTO `inventory_distrito` (`id`, `descripcion`, `departamento_id`) VALUES (54, 'ITAPE', 5);
INSERT INTO `inventory_distrito` (`id`, `descripcion`, `departamento_id`) VALUES (55, 'ITURBE', 5);
INSERT INTO `inventory_distrito` (`id`, `descripcion`, `departamento_id`) VALUES (56, 'MBOCAYATY', 5);
INSERT INTO `inventory_distrito` (`id`, `descripcion`, `departamento_id`) VALUES (57, 'NATALICIO TALAVERA', 5);
INSERT INTO `inventory_distrito` (`id`, `descripcion`, `departamento_id`) VALUES (58, 'ÑUMI', 5);
INSERT INTO `inventory_distrito` (`id`, `descripcion`, `departamento_id`) VALUES (59, 'YATAITY', 5);
INSERT INTO `inventory_distrito` (`id`, `descripcion`, `departamento_id`) VALUES (60, 'DR. BOTREL', 5);
INSERT INTO `inventory_distrito` (`id`, `descripcion`, `departamento_id`) VALUES (61, 'CNEL. OVIEDO', 6);
INSERT INTO `inventory_distrito` (`id`, `descripcion`, `departamento_id`) VALUES (62, 'CAAGUAZU', 6);
INSERT INTO `inventory_distrito` (`id`, `descripcion`, `departamento_id`) VALUES (63, 'CARAYAO', 6);
INSERT INTO `inventory_distrito` (`id`, `descripcion`, `departamento_id`) VALUES (64, 'CECILIO BAEZ', 6);
INSERT INTO `inventory_distrito` (`id`, `descripcion`, `departamento_id`) VALUES (65, 'NUEVA LONDRES', 6);
INSERT INTO `inventory_distrito` (`id`, `descripcion`, `departamento_id`) VALUES (66, 'SAN JOAQUIN', 6);
INSERT INTO `inventory_distrito` (`id`, `descripcion`, `departamento_id`) VALUES (67, 'SAN JOSE DE LOS ARROYOS', 6);
INSERT INTO `inventory_distrito` (`id`, `descripcion`, `departamento_id`) VALUES (68, 'YHU', 6);
INSERT INTO `inventory_distrito` (`id`, `descripcion`, `departamento_id`) VALUES (69, 'JUAN MANUEL FRUTOS', 6);
INSERT INTO `inventory_distrito` (`id`, `descripcion`, `departamento_id`) VALUES (70, 'REPATRIACION', 6);
INSERT INTO `inventory_distrito` (`id`, `descripcion`, `departamento_id`) VALUES (71, 'SANTA ROSA DEL MBUTUY', 6);
INSERT INTO `inventory_distrito` (`id`, `descripcion`, `departamento_id`) VALUES (72, 'J. EULOGIO ESTIGARRIBIA', 6);
INSERT INTO `inventory_distrito` (`id`, `descripcion`, `departamento_id`) VALUES (73, 'JOSE D. OCAMPOS', 6);
INSERT INTO `inventory_distrito` (`id`, `descripcion`, `departamento_id`) VALUES (74, 'R.I.3 CORRALES', 6);
INSERT INTO `inventory_distrito` (`id`, `descripcion`, `departamento_id`) VALUES (75, 'RAUL A. OVIEDO', 6);
INSERT INTO `inventory_distrito` (`id`, `descripcion`, `departamento_id`) VALUES (76, 'MCAL.F.SOLANO LOPEZ', 6);
INSERT INTO `inventory_distrito` (`id`, `descripcion`, `departamento_id`) VALUES (77, 'CAAZAPA', 7);
INSERT INTO `inventory_distrito` (`id`, `descripcion`, `departamento_id`) VALUES (78, 'BUENA VISTA', 7);
INSERT INTO `inventory_distrito` (`id`, `descripcion`, `departamento_id`) VALUES (79, 'GRAL. H. MORINIGO', 7);
INSERT INTO `inventory_distrito` (`id`, `descripcion`, `departamento_id`) VALUES (80, 'MACIEL', 7);
INSERT INTO `inventory_distrito` (`id`, `descripcion`, `departamento_id`) VALUES (81, 'MOISES BERTONI', 7);
INSERT INTO `inventory_distrito` (`id`, `descripcion`, `departamento_id`) VALUES (82, 'SAN JUAN NEPOMUCENO', 7);
INSERT INTO `inventory_distrito` (`id`, `descripcion`, `departamento_id`) VALUES (83, 'ABAI', 7);
INSERT INTO `inventory_distrito` (`id`, `descripcion`, `departamento_id`) VALUES (84, 'TAVAI', 7);
INSERT INTO `inventory_distrito` (`id`, `descripcion`, `departamento_id`) VALUES (85, 'YEGROS', 7);
INSERT INTO `inventory_distrito` (`id`, `descripcion`, `departamento_id`) VALUES (86, 'YUTY', 7);
INSERT INTO `inventory_distrito` (`id`, `descripcion`, `departamento_id`) VALUES (87, 'ENCARNACION', 8);
INSERT INTO `inventory_distrito` (`id`, `descripcion`, `departamento_id`) VALUES (88, 'BELLA VISTA', 8);
INSERT INTO `inventory_distrito` (`id`, `descripcion`, `departamento_id`) VALUES (89, 'CAMBYRETA', 8);
INSERT INTO `inventory_distrito` (`id`, `descripcion`, `departamento_id`) VALUES (90, 'CAPITAN MEZA', 8);
INSERT INTO `inventory_distrito` (`id`, `descripcion`, `departamento_id`) VALUES (91, 'CARMEN DEL PARANA', 8);
INSERT INTO `inventory_distrito` (`id`, `descripcion`, `departamento_id`) VALUES (92, 'CAPITAN MIRANDA', 8);
INSERT INTO `inventory_distrito` (`id`, `descripcion`, `departamento_id`) VALUES (93, 'CORONEL BOGADO', 8);
INSERT INTO `inventory_distrito` (`id`, `descripcion`, `departamento_id`) VALUES (94, 'FRAM', 8);
INSERT INTO `inventory_distrito` (`id`, `descripcion`, `departamento_id`) VALUES (95, 'GRAL. ARTIGAS', 8);
INSERT INTO `inventory_distrito` (`id`, `descripcion`, `departamento_id`) VALUES (96, 'GRAL. DELGADO', 8);
INSERT INTO `inventory_distrito` (`id`, `descripcion`, `departamento_id`) VALUES (97, 'HOHENAU', 8);
INSERT INTO `inventory_distrito` (`id`, `descripcion`, `departamento_id`) VALUES (98, 'JESUS', 8);
INSERT INTO `inventory_distrito` (`id`, `descripcion`, `departamento_id`) VALUES (99, 'OBLIGADO', 8);
INSERT INTO `inventory_distrito` (`id`, `descripcion`, `departamento_id`) VALUES (100, 'SAN COSME Y DAMIAN', 8);
INSERT INTO `inventory_distrito` (`id`, `descripcion`, `departamento_id`) VALUES (101, 'SAN PEDRO DEL PARANA', 8);
INSERT INTO `inventory_distrito` (`id`, `descripcion`, `departamento_id`) VALUES (102, 'NUEVA ALBORADA', 8);
INSERT INTO `inventory_distrito` (`id`, `descripcion`, `departamento_id`) VALUES (103, 'TRINIDAD', 8);
INSERT INTO `inventory_distrito` (`id`, `descripcion`, `departamento_id`) VALUES (104, 'NATALIO', 8);
INSERT INTO `inventory_distrito` (`id`, `descripcion`, `departamento_id`) VALUES (105, 'JOSE LEANDRO OVIEDO', 8);
INSERT INTO `inventory_distrito` (`id`, `descripcion`, `departamento_id`) VALUES (106, 'SAN RAFAEL DEL PARANA', 8);
INSERT INTO `inventory_distrito` (`id`, `descripcion`, `departamento_id`) VALUES (107, 'CARLOS A. LOPEZ', 8);
INSERT INTO `inventory_distrito` (`id`, `descripcion`, `departamento_id`) VALUES (108, 'JULIO D. OTAÑO', 8);
INSERT INTO `inventory_distrito` (`id`, `descripcion`, `departamento_id`) VALUES (109, 'EDELIRA', 8);
INSERT INTO `inventory_distrito` (`id`, `descripcion`, `departamento_id`) VALUES (110, 'SAN JUAN DEL PARANA', 8);
INSERT INTO `inventory_distrito` (`id`, `descripcion`, `departamento_id`) VALUES (111, 'LA PAZ', 8);
INSERT INTO `inventory_distrito` (`id`, `descripcion`, `departamento_id`) VALUES (112, 'TOMAS R. PEREIRA', 8);
INSERT INTO `inventory_distrito` (`id`, `descripcion`, `departamento_id`) VALUES (113, 'YATYTAY', 8);
INSERT INTO `inventory_distrito` (`id`, `descripcion`, `departamento_id`) VALUES (114, 'HERIBERTA S.DE IGLESIAS', 8);
INSERT INTO `inventory_distrito` (`id`, `descripcion`, `departamento_id`) VALUES (115, 'SAN JUAN BAUTISTA', 9);
INSERT INTO `inventory_distrito` (`id`, `descripcion`, `departamento_id`) VALUES (116, 'AYOLAS', 9);
INSERT INTO `inventory_distrito` (`id`, `descripcion`, `departamento_id`) VALUES (117, 'SAN IGNACIO', 9);
INSERT INTO `inventory_distrito` (`id`, `descripcion`, `departamento_id`) VALUES (118, 'SAN MIGUEL', 9);
INSERT INTO `inventory_distrito` (`id`, `descripcion`, `departamento_id`) VALUES (119, 'SAN PATRICIO', 9);
INSERT INTO `inventory_distrito` (`id`, `descripcion`, `departamento_id`) VALUES (120, 'SANTIAGO', 9);
INSERT INTO `inventory_distrito` (`id`, `descripcion`, `departamento_id`) VALUES (121, 'SANTA MARIA', 9);
INSERT INTO `inventory_distrito` (`id`, `descripcion`, `departamento_id`) VALUES (122, 'SANTA ROSA', 9);
INSERT INTO `inventory_distrito` (`id`, `descripcion`, `departamento_id`) VALUES (123, 'VILLA FLORIDA', 9);
INSERT INTO `inventory_distrito` (`id`, `descripcion`, `departamento_id`) VALUES (124, 'YABEBYRY', 9);
INSERT INTO `inventory_distrito` (`id`, `descripcion`, `departamento_id`) VALUES (125, 'PARAGUARI', 10);
INSERT INTO `inventory_distrito` (`id`, `descripcion`, `departamento_id`) VALUES (126, 'ACAHAY', 10);
INSERT INTO `inventory_distrito` (`id`, `descripcion`, `departamento_id`) VALUES (127, 'CAAPUCU', 10);
INSERT INTO `inventory_distrito` (`id`, `descripcion`, `departamento_id`) VALUES (128, 'CABALLERO', 10);
INSERT INTO `inventory_distrito` (`id`, `descripcion`, `departamento_id`) VALUES (129, 'CARAPEGUA', 10);
INSERT INTO `inventory_distrito` (`id`, `descripcion`, `departamento_id`) VALUES (130, 'LA COLMENA', 10);
INSERT INTO `inventory_distrito` (`id`, `descripcion`, `departamento_id`) VALUES (131, 'ESCOBAR', 10);
INSERT INTO `inventory_distrito` (`id`, `descripcion`, `departamento_id`) VALUES (132, 'MBUYAPEY', 10);
INSERT INTO `inventory_distrito` (`id`, `descripcion`, `departamento_id`) VALUES (133, 'PIRAYU', 10);
INSERT INTO `inventory_distrito` (`id`, `descripcion`, `departamento_id`) VALUES (134, 'QUIINDY', 10);
INSERT INTO `inventory_distrito` (`id`, `descripcion`, `departamento_id`) VALUES (135, 'ROQUE GONZALEZ', 10);
INSERT INTO `inventory_distrito` (`id`, `descripcion`, `departamento_id`) VALUES (136, 'SAPUCAI', 10);
INSERT INTO `inventory_distrito` (`id`, `descripcion`, `departamento_id`) VALUES (137, 'YBYCUI', 10);
INSERT INTO `inventory_distrito` (`id`, `descripcion`, `departamento_id`) VALUES (138, 'QUYQUYHO', 10);
INSERT INTO `inventory_distrito` (`id`, `descripcion`, `departamento_id`) VALUES (139, 'YBYTYMI', 10);
INSERT INTO `inventory_distrito` (`id`, `descripcion`, `departamento_id`) VALUES (140, 'TEBICUARY MI', 10);
INSERT INTO `inventory_distrito` (`id`, `descripcion`, `departamento_id`) VALUES (141, 'YAGUARON', 10);
INSERT INTO `inventory_distrito` (`id`, `descripcion`, `departamento_id`) VALUES (142, 'HERNANDARIAS', 11);
INSERT INTO `inventory_distrito` (`id`, `descripcion`, `departamento_id`) VALUES (143, 'DOMINGO MARTINEZ DE IRALA', 11);
INSERT INTO `inventory_distrito` (`id`, `descripcion`, `departamento_id`) VALUES (144, 'ÑACUNDAY', 11);
INSERT INTO `inventory_distrito` (`id`, `descripcion`, `departamento_id`) VALUES (145, 'CIUDAD DEL ESTE', 11);
INSERT INTO `inventory_distrito` (`id`, `descripcion`, `departamento_id`) VALUES (146, 'JUAN LEON MALLORQUIN', 11);
INSERT INTO `inventory_distrito` (`id`, `descripcion`, `departamento_id`) VALUES (147, 'ITAKYRY', 11);
INSERT INTO `inventory_distrito` (`id`, `descripcion`, `departamento_id`) VALUES (148, 'JUAN E.O LEARY', 11);
INSERT INTO `inventory_distrito` (`id`, `descripcion`, `departamento_id`) VALUES (149, 'PUERTO PTE.FRANCO', 11);
INSERT INTO `inventory_distrito` (`id`, `descripcion`, `departamento_id`) VALUES (150, 'YGUAZU', 11);
INSERT INTO `inventory_distrito` (`id`, `descripcion`, `departamento_id`) VALUES (151, 'SAN CRISTOBAL', 11);
INSERT INTO `inventory_distrito` (`id`, `descripcion`, `departamento_id`) VALUES (152, 'AREGUA', 12);
INSERT INTO `inventory_distrito` (`id`, `descripcion`, `departamento_id`) VALUES (153, 'CAPIATA', 12);
INSERT INTO `inventory_distrito` (`id`, `descripcion`, `departamento_id`) VALUES (154, 'FERNANDO DE LA MORA', 12);
INSERT INTO `inventory_distrito` (`id`, `descripcion`, `departamento_id`) VALUES (155, 'GUARAMBARE', 12);
INSERT INTO `inventory_distrito` (`id`, `descripcion`, `departamento_id`) VALUES (156, 'ITA', 12);
INSERT INTO `inventory_distrito` (`id`, `descripcion`, `departamento_id`) VALUES (157, 'ITAUGUA', 12);
INSERT INTO `inventory_distrito` (`id`, `descripcion`, `departamento_id`) VALUES (158, 'LIMPIO', 12);
INSERT INTO `inventory_distrito` (`id`, `descripcion`, `departamento_id`) VALUES (159, 'LUQUE', 12);
INSERT INTO `inventory_distrito` (`id`, `descripcion`, `departamento_id`) VALUES (160, 'MARIANO ROQUE ALONSO', 12);
INSERT INTO `inventory_distrito` (`id`, `descripcion`, `departamento_id`) VALUES (161, 'ÑEMBY', 12);
INSERT INTO `inventory_distrito` (`id`, `descripcion`, `departamento_id`) VALUES (162, 'NUEVA ITALIA', 12);
INSERT INTO `inventory_distrito` (`id`, `descripcion`, `departamento_id`) VALUES (163, 'SAN ANTONIO', 12);
INSERT INTO `inventory_distrito` (`id`, `descripcion`, `departamento_id`) VALUES (164, 'SAN LORENZO', 12);
INSERT INTO `inventory_distrito` (`id`, `descripcion`, `departamento_id`) VALUES (165, 'VILLA ELISA', 12);
INSERT INTO `inventory_distrito` (`id`, `descripcion`, `departamento_id`) VALUES (166, 'VILLETA', 12);
INSERT INTO `inventory_distrito` (`id`, `descripcion`, `departamento_id`) VALUES (167, 'YPACARAI', 12);
INSERT INTO `inventory_distrito` (`id`, `descripcion`, `departamento_id`) VALUES (168, 'YPANE', 12);
INSERT INTO `inventory_distrito` (`id`, `descripcion`, `departamento_id`) VALUES (169, 'LAMBARE', 12);
INSERT INTO `inventory_distrito` (`id`, `descripcion`, `departamento_id`) VALUES (170, 'J.AUGUSTO SALDIVAR', 12);
INSERT INTO `inventory_distrito` (`id`, `descripcion`, `departamento_id`) VALUES (171, 'PILAR', 13);
INSERT INTO `inventory_distrito` (`id`, `descripcion`, `departamento_id`) VALUES (172, 'ALBERDI', 13);
INSERT INTO `inventory_distrito` (`id`, `descripcion`, `departamento_id`) VALUES (173, 'CERRITO', 13);
INSERT INTO `inventory_distrito` (`id`, `descripcion`, `departamento_id`) VALUES (174, 'DESMOCHADOS', 13);
INSERT INTO `inventory_distrito` (`id`, `descripcion`, `departamento_id`) VALUES (175, 'GUAZU CUA', 13);
INSERT INTO `inventory_distrito` (`id`, `descripcion`, `departamento_id`) VALUES (176, 'HUMAITA', 13);
INSERT INTO `inventory_distrito` (`id`, `descripcion`, `departamento_id`) VALUES (177, 'ISLA UMBU', 13);
INSERT INTO `inventory_distrito` (`id`, `descripcion`, `departamento_id`) VALUES (178, 'LAURELES', 13);
INSERT INTO `inventory_distrito` (`id`, `descripcion`, `departamento_id`) VALUES (179, 'PASO DE PATRIA', 13);
INSERT INTO `inventory_distrito` (`id`, `descripcion`, `departamento_id`) VALUES (180, 'MAYOR J.D.MARTINEZ', 13);
INSERT INTO `inventory_distrito` (`id`, `descripcion`, `departamento_id`) VALUES (181, 'SAN JUAN DE ÑEEMBUCU', 13);
INSERT INTO `inventory_distrito` (`id`, `descripcion`, `departamento_id`) VALUES (182, 'TACUARAS', 13);
INSERT INTO `inventory_distrito` (`id`, `descripcion`, `departamento_id`) VALUES (183, 'VILLA OLIVA', 13);
INSERT INTO `inventory_distrito` (`id`, `descripcion`, `departamento_id`) VALUES (184, 'VILLALBIN', 13);
INSERT INTO `inventory_distrito` (`id`, `descripcion`, `departamento_id`) VALUES (185, 'PEDRO JUAN CABALLERO', 14);
INSERT INTO `inventory_distrito` (`id`, `descripcion`, `departamento_id`) VALUES (186, 'BELLA VISTA', 14);
INSERT INTO `inventory_distrito` (`id`, `descripcion`, `departamento_id`) VALUES (187, 'CAPITAN BADO', 14);
INSERT INTO `inventory_distrito` (`id`, `descripcion`, `departamento_id`) VALUES (188, 'VILLA HAYES', 15);
INSERT INTO `inventory_distrito` (`id`, `descripcion`, `departamento_id`) VALUES (189, 'BENJAMIN ACEVAL(MONTE SOCIEDAD', 15);
INSERT INTO `inventory_distrito` (`id`, `descripcion`, `departamento_id`) VALUES (190, 'PTO.PINAZCO', 15);
INSERT INTO `inventory_distrito` (`id`, `descripcion`, `departamento_id`) VALUES (191, 'NANAWA', 15);
INSERT INTO `inventory_distrito` (`id`, `descripcion`, `departamento_id`) VALUES (192, 'MCAL.ESTIGARRIBIA', 16);
INSERT INTO `inventory_distrito` (`id`, `descripcion`, `departamento_id`) VALUES (193, 'BOQUERON', 16);
INSERT INTO `inventory_distrito` (`id`, `descripcion`, `departamento_id`) VALUES (194, 'PEDRO P.PEÑA', 16);
INSERT INTO `inventory_distrito` (`id`, `descripcion`, `departamento_id`) VALUES (195, 'FUERTE OLIMPO', 17);
INSERT INTO `inventory_distrito` (`id`, `descripcion`, `departamento_id`) VALUES (196, 'BAHIA NEGRA', 17);
INSERT INTO `inventory_distrito` (`id`, `descripcion`, `departamento_id`) VALUES (197, 'SAN ISIDRO DEL CURUGUATY', 18);
INSERT INTO `inventory_distrito` (`id`, `descripcion`, `departamento_id`) VALUES (198, 'VILLA YGATIMI', 18);
INSERT INTO `inventory_distrito` (`id`, `descripcion`, `departamento_id`) VALUES (199, 'YPEJHU', 18);
INSERT INTO `inventory_distrito` (`id`, `descripcion`, `departamento_id`) VALUES (200, 'CORPUS CHRISTI', 18);
INSERT INTO `inventory_distrito` (`id`, `descripcion`, `departamento_id`) VALUES (201, 'ITANARA', 18);
INSERT INTO `inventory_distrito` (`id`, `descripcion`, `departamento_id`) VALUES (202, 'FRANCISCO CABALLERO ALVAREZ', 18);
INSERT INTO `inventory_distrito` (`id`, `descripcion`, `departamento_id`) VALUES (203, 'GRAL.JOSE EDUVIGIS DIAZ', 13);
INSERT INTO `inventory_distrito` (`id`, `descripcion`, `departamento_id`) VALUES (205, 'VILLA FRANCA', 13);
INSERT INTO `inventory_distrito` (`id`, `descripcion`, `departamento_id`) VALUES (206, 'POZO COLORADO', 15);
INSERT INTO `inventory_distrito` (`id`, `descripcion`, `departamento_id`) VALUES (207, 'SALTO DEL GUAIRA', 18);
INSERT INTO `inventory_distrito` (`id`, `descripcion`, `departamento_id`) VALUES (209, 'SANTA RITA', 11);
INSERT INTO `inventory_distrito` (`id`, `descripcion`, `departamento_id`) VALUES (210, 'MINGA GUAZU', 11);
INSERT INTO `inventory_distrito` (`id`, `descripcion`, `departamento_id`) VALUES (211, 'LOS CEDRALES', 11);
INSERT INTO `inventory_distrito` (`id`, `descripcion`, `departamento_id`) VALUES (212, 'SAN ALBERTO', 11);
INSERT INTO `inventory_distrito` (`id`, `descripcion`, `departamento_id`) VALUES (213, 'MINGA PORA', 11);
INSERT INTO `inventory_distrito` (`id`, `descripcion`, `departamento_id`) VALUES (214, 'MBOCAYATY DEL YHAGUY', 4);
INSERT INTO `inventory_distrito` (`id`, `descripcion`, `departamento_id`) VALUES (215, 'NARANJAL', 11);
INSERT INTO `inventory_distrito` (`id`, `descripcion`, `departamento_id`) VALUES (216, 'SANTA ROSA DEL MONDAY', 11);
INSERT INTO `inventory_distrito` (`id`, `descripcion`, `departamento_id`) VALUES (217, 'IRUÑA', 11);
INSERT INTO `inventory_distrito` (`id`, `descripcion`, `departamento_id`) VALUES (218, 'PUERTO CASADO', 17);
INSERT INTO `inventory_distrito` (`id`, `descripcion`, `departamento_id`) VALUES (219, 'MBARACAYU', 11);
INSERT INTO `inventory_distrito` (`id`, `descripcion`, `departamento_id`) VALUES (220, 'GUAYAIBI', 3);
INSERT INTO `inventory_distrito` (`id`, `descripcion`, `departamento_id`) VALUES (221, 'PIRAPO', 8);
INSERT INTO `inventory_distrito` (`id`, `descripcion`, `departamento_id`) VALUES (223, 'PUERTO GUARANI', 17);
INSERT INTO `inventory_distrito` (`id`, `descripcion`, `departamento_id`) VALUES (225, 'PASO YOBAY', 5);
INSERT INTO `inventory_distrito` (`id`, `descripcion`, `departamento_id`) VALUES (226, 'CAPIIBARY', 3);
INSERT INTO `inventory_distrito` (`id`, `descripcion`, `departamento_id`) VALUES (227, '3 DE FEBRERO', 6);
INSERT INTO `inventory_distrito` (`id`, `descripcion`, `departamento_id`) VALUES (228, 'SIMON BOLIVAR', 6);
INSERT INTO `inventory_distrito` (`id`, `descripcion`, `departamento_id`) VALUES (229, 'LA PASTORA', 6);
INSERT INTO `inventory_distrito` (`id`, `descripcion`, `departamento_id`) VALUES (231, 'VILLALBIN', 13);
INSERT INTO `inventory_distrito` (`id`, `descripcion`, `departamento_id`) VALUES (232, 'ITAPUA POTY', 8);
INSERT INTO `inventory_distrito` (`id`, `descripcion`, `departamento_id`) VALUES (233, 'MAYOR PABLO LAGERENZA', 17);
INSERT INTO `inventory_distrito` (`id`, `descripcion`, `departamento_id`) VALUES (234, 'GRAL. EUGENIO A. GARAY', 16);
INSERT INTO `inventory_distrito` (`id`, `descripcion`, `departamento_id`) VALUES (235, 'LA PALOMA', 18);
INSERT INTO `inventory_distrito` (`id`, `descripcion`, `departamento_id`) VALUES (236, 'KATUETE', 18);
INSERT INTO `inventory_distrito` (`id`, `descripcion`, `departamento_id`) VALUES (237, 'VAQUERIA', 6);
INSERT INTO `inventory_distrito` (`id`, `descripcion`, `departamento_id`) VALUES (238, 'NUEVA ESPERANZA', 18);
INSERT INTO `inventory_distrito` (`id`, `descripcion`, `departamento_id`) VALUES (239, 'SANTA FE DEL PARANA', 11);
INSERT INTO `inventory_distrito` (`id`, `descripcion`, `departamento_id`) VALUES (240, 'NUEVA ESPERANZA', 11);
INSERT INTO `inventory_distrito` (`id`, `descripcion`, `departamento_id`) VALUES (241, 'YASY KAÑY', 18);
INSERT INTO `inventory_distrito` (`id`, `descripcion`, `departamento_id`) VALUES (242, 'JOSE FALCON', 15);
INSERT INTO `inventory_distrito` (`id`, `descripcion`, `departamento_id`) VALUES (243, 'FEDERICO CHAVEZ', 8);
INSERT INTO `inventory_distrito` (`id`, `descripcion`, `departamento_id`) VALUES (244, 'ESCULIES', 6);
INSERT INTO `inventory_distrito` (`id`, `descripcion`, `departamento_id`) VALUES (245, 'YRYBUCUA', 3);
INSERT INTO `inventory_distrito` (`id`, `descripcion`, `departamento_id`) VALUES (246, 'SIN EQUIVALENCIA', 5);
INSERT INTO `inventory_distrito` (`id`, `descripcion`, `departamento_id`) VALUES (259, 'FILADELFIA', 16);
INSERT INTO `inventory_distrito` (`id`, `descripcion`, `departamento_id`) VALUES (265, 'TEBICUARY', 5);
INSERT INTO `inventory_distrito` (`id`, `descripcion`, `departamento_id`) VALUES (270, 'SARGENTO JOSE FELIX LOPEZ', 2);
INSERT INTO `inventory_distrito` (`id`, `descripcion`, `departamento_id`) VALUES (271, 'YBYRAROBANA', 18);
INSERT INTO `inventory_distrito` (`id`, `descripcion`, `departamento_id`) VALUES (272, '3 DE MAYO', 7);
INSERT INTO `inventory_distrito` (`id`, `descripcion`, `departamento_id`) VALUES (274, 'YBY PYTA', 18);
INSERT INTO `inventory_distrito` (`id`, `descripcion`, `departamento_id`) VALUES (275, 'TEMBIAPORA', 6);
INSERT INTO `inventory_distrito` (`id`, `descripcion`, `departamento_id`) VALUES (277, 'LOMA PYTA', 12);
INSERT INTO `inventory_distrito` (`id`, `descripcion`, `departamento_id`) VALUES (278, 'KARAPAI', 14);
