# Generated by Django 3.1 on 2022-02-09 14:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Acopio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(verbose_name='Fecha')),
                ('comprobante', models.CharField(max_length=30, verbose_name='Comprobante')),
                ('pBruto', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Peso Bruto')),
                ('pTara', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Peso Tara')),
                ('pDescuento', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Peso Descuento')),
                ('pBonificacion', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Peso Bonificación')),
                ('esTransportadoraPropia', models.BooleanField(default=False, verbose_name='Es Transportadora Propia?')),
                ('esVigente', models.BooleanField(default=True, verbose_name='Vigente?')),
                ('observacion', models.CharField(blank=True, max_length=300, null=True, verbose_name='Observación')),
            ],
        ),
        migrations.CreateModel(
            name='ActividadAgricola',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaDocumento', models.DateField(verbose_name='Fecha')),
                ('fechaHoraRegistro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha Hora Registro')),
                ('observacion', models.CharField(blank=True, max_length=300, null=True, verbose_name='Observación')),
                ('esVigente', models.BooleanField(default=True, verbose_name='Vigente?')),
                ('esServicioContratado', models.BooleanField(default=False, verbose_name='Es contratado?')),
                ('cantidadTrabajada', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Cant HA Trabajada')),
            ],
        ),
        migrations.CreateModel(
            name='AjusteStock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaDocumento', models.DateField(verbose_name='Fecha')),
                ('fechaHoraRegistro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha Hora Registro')),
                ('comprobante', models.CharField(max_length=15, verbose_name='Comprobante')),
                ('observacion', models.CharField(blank=True, max_length=300, null=True, verbose_name='Observación')),
            ],
        ),
        migrations.CreateModel(
            name='AperturaCaja',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observacion', models.CharField(blank=True, max_length=300, null=True, verbose_name='Observación')),
                ('fechaHoraRegistro', models.DateTimeField(auto_now_add=True, verbose_name='Fec Hr Apertura')),
                ('estaCerrado', models.BooleanField(default=False, verbose_name='Esta Cerrado?')),
                ('montoInicio', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Monto Apertura')),
                ('fechaHoraCierre', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fec Hr Cierre')),
            ],
        ),
        migrations.CreateModel(
            name='Banco',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=200, unique=True, verbose_name='Descripcion')),
            ],
        ),
        migrations.CreateModel(
            name='CalificacionAgricola',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=200, unique=True, verbose_name='Descripcion')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=200, verbose_name='Descripcion')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CierreZafra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(verbose_name='Fecha')),
                ('observacion', models.CharField(blank=True, max_length=300, null=True, verbose_name='Observación')),
            ],
        ),
        migrations.CreateModel(
            name='Cobro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaDocumento', models.DateField(verbose_name='Fecha')),
                ('fechaHoraRegistro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha Hora Registro')),
                ('observacion', models.CharField(blank=True, max_length=300, null=True, verbose_name='Observación')),
                ('esVigente', models.BooleanField(default=True, verbose_name='Vigente?')),
                ('montoASaldar', models.DecimalField(decimal_places=0, max_digits=15, verbose_name='Monto A Saldar')),
                ('comprobante', models.CharField(max_length=15, verbose_name='Comprobante')),
                ('aperturaCaja', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='inventory.aperturacaja', verbose_name='Apertura Caja')),
            ],
        ),
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaDocumento', models.DateField(verbose_name='Fecha Documento')),
                ('fechaHoraRegistro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha Hora Registro')),
                ('comprobante', models.CharField(max_length=15, verbose_name='Comprobante')),
                ('timbrado', models.CharField(max_length=8, verbose_name='Timbrado')),
                ('esCredito', models.BooleanField(default=False, verbose_name='Es Crédito?')),
                ('esVigente', models.BooleanField(default=True, verbose_name='Vigente?')),
                ('observacion', models.CharField(blank=True, max_length=300, null=True, verbose_name='Observación')),
            ],
        ),
        migrations.CreateModel(
            name='Cuenta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=200, unique=True, verbose_name='Descripcion')),
                ('esBanco', models.BooleanField(default=False, verbose_name='Es Banco?')),
                ('nroCuenta', models.CharField(blank=True, max_length=200, null=True, verbose_name='Nro Cuenta')),
                ('banco', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='inventory.banco', verbose_name='Banco')),
            ],
        ),
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=200, unique=True, verbose_name='Descripcion')),
            ],
        ),
        migrations.CreateModel(
            name='Deposito',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=200, unique=True, verbose_name='Descripcion')),
                ('esPlantaAcopiadora', models.BooleanField(default=False, verbose_name='Es Planta Acopiadora?')),
            ],
        ),
        migrations.CreateModel(
            name='Distrito',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=200, verbose_name='Descripcion')),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='inventory.departamento', verbose_name='Departamento')),
            ],
        ),
        migrations.CreateModel(
            name='Finca',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=200, unique=True, verbose_name='Descripcion')),
                ('dimensionHa', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Dimension Ha')),
                ('ubicacion', models.CharField(max_length=200, verbose_name='Ubicacion')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=200, verbose_name='Descripcion')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio')),
                ('costo', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Costo')),
                ('ultimoCosto', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Ult. Costo')),
                ('esActivo', models.BooleanField(verbose_name='Activo?')),
                ('codigoBarra', models.CharField(max_length=20, verbose_name='Cód Barra')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='inventory.categoria', verbose_name='Categoria')),
            ],
        ),
        migrations.CreateModel(
            name='LiquidacionAgricola',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaDocumento', models.DateField(verbose_name='Fecha')),
                ('fechaHoraRegistro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha Hora Registro')),
                ('observacion', models.CharField(blank=True, max_length=300, null=True, verbose_name='Observación')),
                ('esVigente', models.BooleanField(default=True, verbose_name='Vigente?')),
                ('precioUnitario', models.DecimalField(decimal_places=0, max_digits=15, verbose_name='Precio')),
                ('tipo', models.CharField(choices=[('ACOPIOS', 'LIQUIDACION DE ACOPIOS'), ('ACTIVIDADES AGRICOLAS', 'LIQUIDACION DE ACTIVIDADES AGRICOLAS')], max_length=50, verbose_name='Tipo Liquidación')),
            ],
        ),
        migrations.CreateModel(
            name='Localidad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=200, verbose_name='Descripcion')),
                ('distrito', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='inventory.distrito', verbose_name='Distrito')),
            ],
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=200, verbose_name='Descripcion')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='NotaCreditoEmitida',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaDocumento', models.DateField(verbose_name='Fecha Documento')),
                ('fechaHoraRegistro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha Hora Registro')),
                ('comprobante', models.CharField(max_length=15, verbose_name='Comprobante')),
                ('timbrado', models.CharField(max_length=8, verbose_name='Timbrado')),
                ('esCredito', models.BooleanField(default=False, verbose_name='Es Crédito?')),
                ('esVigente', models.BooleanField(default=True, verbose_name='Vigente?')),
                ('observacion', models.CharField(blank=True, max_length=300, null=True, verbose_name='Observación')),
            ],
        ),
        migrations.CreateModel(
            name='NotaCreditoRecibida',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaDocumento', models.DateField(verbose_name='Fecha Documento')),
                ('fechaHoraRegistro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha Hora Registro')),
                ('comprobante', models.CharField(max_length=15, verbose_name='Comprobante')),
                ('timbrado', models.CharField(max_length=8, verbose_name='Timbrado')),
                ('esCredito', models.BooleanField(default=False, verbose_name='Es Crédito?')),
                ('esVigente', models.BooleanField(default=True, verbose_name='Vigente?')),
                ('observacion', models.CharField(blank=True, max_length=300, null=True, verbose_name='Observación')),
                ('compra', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='inventory.compra', verbose_name='Compra')),
                ('cuenta', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='inventory.cuenta', verbose_name='Cuenta')),
                ('deposito', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='inventory.deposito', verbose_name='Deposito')),
            ],
        ),
        migrations.CreateModel(
            name='NotaDebitoEmitida',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaDocumento', models.DateField(verbose_name='Fecha Documento')),
                ('fechaHoraRegistro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha Hora Registro')),
                ('comprobante', models.CharField(max_length=15, verbose_name='Comprobante')),
                ('timbrado', models.CharField(max_length=8, verbose_name='Timbrado')),
                ('esCredito', models.BooleanField(default=False, verbose_name='Es Crédito?')),
                ('esVigente', models.BooleanField(default=True, verbose_name='Vigente?')),
                ('observacion', models.CharField(blank=True, max_length=300, null=True, verbose_name='Observación')),
            ],
        ),
        migrations.CreateModel(
            name='NotaDebitoRecibida',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaDocumento', models.DateField(verbose_name='Fecha Documento')),
                ('fechaHoraRegistro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha Hora Registro')),
                ('comprobante', models.CharField(max_length=15, verbose_name='Comprobante')),
                ('timbrado', models.CharField(max_length=8, verbose_name='Timbrado')),
                ('esCredito', models.BooleanField(default=False, verbose_name='Es Crédito?')),
                ('esVigente', models.BooleanField(default=True, verbose_name='Vigente?')),
                ('observacion', models.CharField(blank=True, max_length=300, null=True, verbose_name='Observación')),
                ('compra', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='inventory.compra', verbose_name='Compra')),
                ('cuenta', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='inventory.cuenta', verbose_name='Cuenta')),
                ('deposito', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='inventory.deposito', verbose_name='Deposito')),
            ],
        ),
        migrations.CreateModel(
            name='OrdenCompra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaDocumento', models.DateField(verbose_name='Fecha Documento')),
                ('esVigente', models.BooleanField(default=True, verbose_name='Vigente?')),
                ('observacion', models.CharField(blank=True, max_length=300, null=True, verbose_name='Observación')),
            ],
        ),
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abreviatura', models.CharField(max_length=200, unique=True, verbose_name='Descripcion')),
                ('descripcion', models.CharField(max_length=200, unique=True, verbose_name='Descripcion')),
            ],
        ),
        migrations.CreateModel(
            name='PedidoCompra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaDocumento', models.DateField(verbose_name='Fecha Documento')),
                ('fechaVencimiento', models.DateField(verbose_name='Fecha Vencimiento')),
                ('esVigente', models.BooleanField(default=True, verbose_name='Vigente?')),
                ('observacion', models.CharField(blank=True, max_length=300, null=True, verbose_name='Observación')),
            ],
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razonSocial', models.CharField(max_length=200, verbose_name='Razon Social')),
                ('documento', models.CharField(max_length=40, verbose_name='Documento')),
                ('direccion', models.CharField(max_length=200, verbose_name='Direccion')),
                ('celular', models.CharField(blank=True, max_length=60, null=True, verbose_name='Celular / Telefono')),
                ('esCliente', models.BooleanField(default=False, verbose_name='Es Cliente?')),
                ('esProveedor', models.BooleanField(default=False, verbose_name='Es Proveedor?')),
                ('esEmpleado', models.BooleanField(default=False, verbose_name='Es Empleado?')),
                ('localidad', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='inventory.localidad', verbose_name='Localidad')),
                ('pais', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='inventory.pais', verbose_name='Pais')),
            ],
        ),
        migrations.CreateModel(
            name='PlanActividadZafra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(verbose_name='Fecha')),
                ('observacion', models.CharField(blank=True, max_length=300, null=True, verbose_name='Observación')),
            ],
        ),
        migrations.CreateModel(
            name='TipoActividadAgricola',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=200, unique=True, verbose_name='Descripcion')),
                ('esCosecha', models.BooleanField(verbose_name='es Cosecha')),
                ('esSiembra', models.BooleanField(verbose_name='es Siembra')),
                ('esResiembra', models.BooleanField(verbose_name='es Resiembra')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TipoImpuesto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=200, unique=True, verbose_name='Descripcion')),
                ('porcentaje', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='% Impuesto')),
                ('esIva', models.BooleanField(max_length=200, verbose_name='es IVA?')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TipoItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=200, unique=True, verbose_name='Descripcion')),
            ],
        ),
        migrations.CreateModel(
            name='TipoMaquinariaAgricola',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=200, unique=True, verbose_name='Descripcion')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaDocumento', models.DateField(verbose_name='Fecha Documento')),
                ('fechaHoraRegistro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha Hora Registro')),
                ('comprobante', models.CharField(max_length=15, verbose_name='Comprobante')),
                ('timbrado', models.CharField(max_length=8, verbose_name='Timbrado')),
                ('esCredito', models.BooleanField(default=False, verbose_name='Es Crédito?')),
                ('esVigente', models.BooleanField(default=True, verbose_name='Vigente?')),
                ('observacion', models.CharField(blank=True, max_length=300, null=True, verbose_name='Observación')),
                ('aperturaCaja', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='inventory.aperturacaja', verbose_name='AperturaCaja')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='inventory.persona', verbose_name='Cliente')),
                ('cuenta', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='inventory.cuenta', verbose_name='Cuenta')),
                ('deposito', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='inventory.deposito', verbose_name='Deposito')),
            ],
        ),
        migrations.CreateModel(
            name='Zafra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=200, verbose_name='Descripcion')),
                ('anho', models.IntegerField(verbose_name='Anho')),
                ('kgEstimado', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Kg Estimado')),
                ('esZafrinha', models.BooleanField(verbose_name='Es Zafriña?')),
                ('estaCerrado', models.BooleanField(default=False, verbose_name='Está Cerrado?')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='inventory.item', verbose_name='Item')),
            ],
        ),
        migrations.CreateModel(
            name='VentaDetalle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Cantidad')),
                ('costo', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Costo')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Precio')),
                ('porcentajeImpuesto', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='% Impuesto')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='inventory.item', verbose_name='Item')),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='inventory.venta')),
            ],
        ),
        migrations.CreateModel(
            name='TransferenciaCuenta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Monto a Transferir')),
                ('fecha', models.DateField(verbose_name='Fecha')),
                ('esVigente', models.BooleanField(default=True, verbose_name='Vigente?')),
                ('observacion', models.CharField(blank=True, max_length=300, null=True, verbose_name='Observación')),
                ('comprobante', models.CharField(default='', max_length=15, verbose_name='Comprobante')),
                ('aperturaCaja', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='inventory.aperturacaja', verbose_name='Cuenta Entrada')),
                ('cuentaEntrada', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='entrada', to='inventory.cuenta', verbose_name='Cuenta Entrada')),
                ('cuentaSalida', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='salida', to='inventory.cuenta', verbose_name='Cuenta Salida')),
            ],
        ),
        migrations.CreateModel(
            name='PlanActividadZafraDetalle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaActividad', models.DateField(verbose_name='Fecha Act.')),
                ('descripcion', models.CharField(blank=True, max_length=300, null=True, verbose_name='Descripción')),
                ('costo', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Costo Estimado')),
                ('finca', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='inventory.finca', verbose_name='Finca')),
                ('planActividadZafra', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='inventory.planactividadzafra')),
                ('tipoActividadAgricola', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='inventory.tipoactividadagricola', verbose_name='Tipo Actividad Agrícola')),
            ],
        ),
        migrations.AddField(
            model_name='planactividadzafra',
            name='zafra',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='inventory.zafra', verbose_name='Zafra'),
        ),
        migrations.CreateModel(
            name='PedidoCompraDetalle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Cantidad')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='inventory.item', verbose_name='Item')),
                ('pedidoCompra', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='inventory.pedidocompra')),
            ],
        ),
        migrations.AddField(
            model_name='pedidocompra',
            name='proveedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='inventory.persona', verbose_name='Proveedor'),
        ),
        migrations.CreateModel(
            name='OrdenCompraDetalle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Cantidad')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Precio')),
                ('descuento', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Descuento')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='inventory.item', verbose_name='Item')),
                ('ordenCompra', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='inventory.ordencompra')),
            ],
        ),
        migrations.AddField(
            model_name='ordencompra',
            name='pedidoCompra',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='inventory.pedidocompra', verbose_name='Pedido Compra'),
        ),
        migrations.AddField(
            model_name='ordencompra',
            name='proveedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='inventory.persona', verbose_name='Proveedor'),
        ),
        migrations.CreateModel(
            name='NotaDebitoRecibidaDetalle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Cantidad')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Precio/Aumento')),
                ('porcentajeImpuesto', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='% Impuesto')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='inventory.item', verbose_name='Item')),
                ('notaDebitoRecibida', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='inventory.notadebitorecibida')),
            ],
        ),
        migrations.AddField(
            model_name='notadebitorecibida',
            name='proveedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='inventory.persona', verbose_name='Proveedor'),
        ),
        migrations.CreateModel(
            name='NotaDebitoEmitidaDetalle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Cantidad')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Costo/Descuento')),
                ('porcentajeImpuesto', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='% Impuesto')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='inventory.item', verbose_name='Item')),
                ('notaDebitoEmitida', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='inventory.notadebitoemitida')),
            ],
        ),
        migrations.AddField(
            model_name='notadebitoemitida',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='inventory.persona', verbose_name='Cliente'),
        ),
        migrations.AddField(
            model_name='notadebitoemitida',
            name='cuenta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='inventory.cuenta', verbose_name='Cuenta'),
        ),
        migrations.AddField(
            model_name='notadebitoemitida',
            name='deposito',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='inventory.deposito', verbose_name='Deposito'),
        ),
        migrations.AddField(
            model_name='notadebitoemitida',
            name='venta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='inventory.venta', verbose_name='Venta'),
        ),
        migrations.CreateModel(
            name='NotaCreditoRecibidaDetalle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Cantidad')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Costo/Descuento')),
                ('esDevolucion', models.BooleanField(default=False, verbose_name='Es Devolución?')),
                ('porcentajeImpuesto', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='% Impuesto')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='inventory.item', verbose_name='Item')),
                ('notaCreditoRecibida', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='inventory.notacreditorecibida')),
            ],
        ),
        migrations.AddField(
            model_name='notacreditorecibida',
            name='proveedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='inventory.persona', verbose_name='Proveedor'),
        ),
        migrations.CreateModel(
            name='NotaCreditoEmitidaDetalle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Cantidad')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Costo/Descuento')),
                ('esDevolucion', models.BooleanField(default=False, verbose_name='Es Devolución?')),
                ('porcentajeImpuesto', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='% Impuesto')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='inventory.item', verbose_name='Item')),
                ('notaCreditoEmitida', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='inventory.notacreditoemitida')),
            ],
        ),
        migrations.AddField(
            model_name='notacreditoemitida',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='inventory.persona', verbose_name='Cliente'),
        ),
        migrations.AddField(
            model_name='notacreditoemitida',
            name='cuenta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='inventory.cuenta', verbose_name='Cuenta'),
        ),
        migrations.AddField(
            model_name='notacreditoemitida',
            name='deposito',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='inventory.deposito', verbose_name='Deposito'),
        ),
        migrations.AddField(
            model_name='notacreditoemitida',
            name='venta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='inventory.venta', verbose_name='Venta'),
        ),
        migrations.CreateModel(
            name='MaquinariaAgricola',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=200, verbose_name='Descripcion')),
                ('esImplemento', models.BooleanField(verbose_name='Es Implemento?')),
                ('admiteImplemento', models.BooleanField(verbose_name='Admite Implemento?')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Precio')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('tipoMaquinariaAgricola', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='inventory.tipomaquinariaagricola', verbose_name='Maquinaria Agrícola Tipo')),
            ],
        ),
        migrations.CreateModel(
            name='Lote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=200, verbose_name='Descripcion')),
                ('dimension', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Dimensión HA')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('finca', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='inventory.finca', verbose_name='Finca')),
                ('zafra', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='inventory.zafra', verbose_name='Zafra')),
            ],
        ),
        migrations.CreateModel(
            name='LiquidacionAgricolaDetalle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Cantidad')),
                ('secuenciaOrigen', models.IntegerField()),
                ('finca', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='inventory.finca', verbose_name='Finca')),
                ('liquidacionAgricola', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='inventory.liquidacionagricola')),
                ('lote', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='inventory.lote', verbose_name='Lote')),
            ],
        ),
        migrations.AddField(
            model_name='liquidacionagricola',
            name='proveedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='inventory.persona', verbose_name='Proveedor'),
        ),
        migrations.AddField(
            model_name='liquidacionagricola',
            name='zafra',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='inventory.zafra', verbose_name='Zafra'),
        ),
        migrations.CreateModel(
            name='ItemMovimiento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Cantidad')),
                ('costo', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Costo')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Precio')),
                ('fechaDocumento', models.DateField(verbose_name='Fecha Documento')),
                ('secuenciaOrigen', models.IntegerField()),
                ('detalleSecuenciaOrigen', models.IntegerField()),
                ('esVigente', models.BooleanField(default=True, verbose_name='Vigente?')),
                ('tipoMovimiento', models.CharField(choices=[('CM', 'COMPRAS'), ('VT', 'VENTAS'), ('A+', 'AJUSTES STOCK +'), ('A-', 'AJUSTES STOCK -'), ('AC', 'ACOPIOS'), ('AA', 'ACTIVIDADES AGRICOLAS'), ('DC', 'DEVOLUCIONES DE COMPRAS'), ('DV', 'DEVOLUCIONES DE VENTAS')], max_length=50, verbose_name='Tipo Mov.')),
                ('deposito', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='inventory.deposito', verbose_name='Deposito')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='inventory.item', verbose_name='Item')),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='marca',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='inventory.marca', verbose_name='Marca'),
        ),
        migrations.AddField(
            model_name='item',
            name='tipoImpuesto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='inventory.tipoimpuesto', verbose_name='Tipo Imp.'),
        ),
        migrations.AddField(
            model_name='item',
            name='tipoItem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='inventory.tipoitem', verbose_name='Tipo Item'),
        ),
        migrations.CreateModel(
            name='CuotaVenta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaVencimiento', models.DateField(verbose_name='Fecha Vencimiento')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Monto')),
                ('saldo', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Saldo')),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='inventory.venta')),
            ],
        ),
        migrations.CreateModel(
            name='CuotaCompra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaVencimiento', models.DateField(verbose_name='Fecha Vencimiento')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Monto')),
                ('saldo', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Saldo')),
                ('compra', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='inventory.compra')),
            ],
        ),
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('costoPactado', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Costo Pactado')),
                ('fecha', models.DateField(verbose_name='Fecha')),
                ('descripcion', models.CharField(max_length=300, verbose_name='Descripción')),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='inventory.persona', verbose_name='Persona')),
                ('zafra', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='inventory.zafra', verbose_name='Zafra')),
            ],
        ),
        migrations.CreateModel(
            name='CompraDetalle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Cantidad')),
                ('costo', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Costo')),
                ('porcentajeImpuesto', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='% Impuesto')),
                ('compra', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='inventory.compra')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='inventory.item', verbose_name='Item')),
            ],
        ),
        migrations.AddField(
            model_name='compra',
            name='cuenta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='inventory.cuenta', verbose_name='Cuenta'),
        ),
        migrations.AddField(
            model_name='compra',
            name='deposito',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='inventory.deposito', verbose_name='Deposito'),
        ),
        migrations.AddField(
            model_name='compra',
            name='proveedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='inventory.persona', verbose_name='Proveedor'),
        ),
        migrations.CreateModel(
            name='CobroMedio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=15, verbose_name='N°')),
                ('comprobante', models.CharField(max_length=15, verbose_name='Comprobante')),
                ('monto', models.DecimalField(decimal_places=0, max_digits=15, verbose_name='Monto')),
                ('observacion', models.CharField(blank=True, max_length=300, null=True, verbose_name='Observación')),
                ('medioCobro', models.CharField(choices=[('CHEQUE DIF', 'CHEQUE DIFERIDO'), ('CHEQUE DIA', 'CHEQUE AL DIA'), ('EFECTIVO', 'EFECTIVO'), ('TRANSFERENCIA', 'TRANSFERENCIA BANCARIA')], max_length=50, verbose_name='Medio Cobro')),
                ('cobro', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='inventory.cobro')),
            ],
        ),
        migrations.CreateModel(
            name='CobroDetalle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cancelacion', models.DecimalField(decimal_places=0, max_digits=15, verbose_name='Cancelacion')),
                ('cobro', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='inventory.cobro')),
                ('cuotaVenta', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='inventory.cuotaventa', verbose_name='Cuota Venta')),
            ],
        ),
        migrations.AddField(
            model_name='cobro',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='cliente', to='inventory.persona', verbose_name='Cliente'),
        ),
        migrations.AddField(
            model_name='cobro',
            name='cobrador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='cobrador', to='inventory.persona', verbose_name='Cobrador'),
        ),
        migrations.AddField(
            model_name='cobro',
            name='cuenta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='inventory.cuenta', verbose_name='Cuenta'),
        ),
        migrations.CreateModel(
            name='CierreZafraDetalle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('haCultivada', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='HA Cultivada')),
                ('cantidadAcopioNeto', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Cant. Acopio')),
                ('rendimiento', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Rendimiento')),
                ('costoTotal', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Costo Total')),
                ('costoHA', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Costo HA')),
                ('costoUnit', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Costo Unit.')),
                ('cierreZafra', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='inventory.cierrezafra')),
                ('finca', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='inventory.finca', verbose_name='Finca')),
            ],
        ),
        migrations.AddField(
            model_name='cierrezafra',
            name='zafra',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='inventory.zafra', verbose_name='Zafra'),
        ),
        migrations.CreateModel(
            name='Arqueo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observacion', models.CharField(blank=True, max_length=300, null=True, verbose_name='Observación')),
                ('fechaHoraRegistro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha Hora Registro')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Monto Retirado')),
                ('aperturaCaja', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='inventory.aperturacaja', verbose_name='Apertura Caja')),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='inventory.persona', verbose_name='Empleado')),
            ],
        ),
        migrations.AddField(
            model_name='aperturacaja',
            name='empleado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='inventory.persona', verbose_name='Empleado'),
        ),
        migrations.CreateModel(
            name='AjusteStockDetalle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Cantidad')),
                ('ajusteStock', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='inventory.ajustestock')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='inventory.item', verbose_name='Item')),
            ],
        ),
        migrations.AddField(
            model_name='ajustestock',
            name='deposito',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='inventory.deposito', verbose_name='Deposito'),
        ),
        migrations.AddField(
            model_name='ajustestock',
            name='empleado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='inventory.persona', verbose_name='Empleado'),
        ),
        migrations.CreateModel(
            name='ActividadAgricolaMaquinariaDetalle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('haTrabajada', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Ha Trabajada')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Precio HA')),
                ('actividadAgricola', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='inventory.actividadagricola')),
                ('maquinaria', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='inventory.maquinariaagricola', verbose_name='Maquinaria')),
            ],
        ),
        migrations.CreateModel(
            name='ActividadAgricolaItemDetalle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('costo', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Costo')),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Cantidad')),
                ('porcentajeImpuesto', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='% Impuesto')),
                ('dosis', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Dosis')),
                ('actividadAgricola', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='inventory.actividadagricola')),
                ('deposito', models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='inventory.deposito', verbose_name='Deposito')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='inventory.item', verbose_name='Item')),
            ],
        ),
        migrations.AddField(
            model_name='actividadagricola',
            name='empleado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='inventory.persona', verbose_name='Empleado'),
        ),
        migrations.AddField(
            model_name='actividadagricola',
            name='finca',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='inventory.finca', verbose_name='Finca'),
        ),
        migrations.AddField(
            model_name='actividadagricola',
            name='lote',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='inventory.lote', verbose_name='Lote'),
        ),
        migrations.AddField(
            model_name='actividadagricola',
            name='tipoActividadAgricola',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='inventory.tipoactividadagricola', verbose_name='Tipo Act. Agrícola'),
        ),
        migrations.AddField(
            model_name='actividadagricola',
            name='zafra',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='inventory.zafra', verbose_name='Zafra'),
        ),
        migrations.CreateModel(
            name='AcopioDetalle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('peso', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Peso')),
                ('acopio', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='inventory.acopio')),
                ('finca', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='inventory.finca', verbose_name='Finca')),
                ('lote', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='inventory.lote', verbose_name='Lote')),
            ],
        ),
        migrations.CreateModel(
            name='AcopioCalificacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grado', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Grado')),
                ('porcentaje', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Porcentaje')),
                ('peso', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Peso')),
                ('acopio', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='inventory.acopio')),
                ('calificacionAgricola', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='inventory.calificacionagricola', verbose_name='Calif. Agrícola')),
            ],
        ),
        migrations.AddField(
            model_name='acopio',
            name='camion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='inventory.maquinariaagricola', verbose_name='Camión'),
        ),
        migrations.AddField(
            model_name='acopio',
            name='conductor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='inventory.persona', verbose_name='Conductor'),
        ),
        migrations.AddField(
            model_name='acopio',
            name='deposito',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='inventory.deposito', verbose_name='Depósito'),
        ),
        migrations.AddField(
            model_name='acopio',
            name='zafra',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='inventory.zafra', verbose_name='Zafra'),
        ),
    ]
