# Generated by Django 3.1 on 2021-12-03 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='costo',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Costo'),
        ),
        migrations.AlterField(
            model_name='item',
            name='ultimoCosto',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Último Costo'),
        ),
    ]
