# Generated by Django 3.1 on 2022-02-15 10:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acopio',
            name='pBonificacion',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Peso Bonif.'),
        ),
        migrations.AlterField(
            model_name='acopio',
            name='pBruto',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Peso Bruto'),
        ),
        migrations.AlterField(
            model_name='acopio',
            name='pDescuento',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Peso Desc.'),
        ),
        migrations.AlterField(
            model_name='acopio',
            name='pTara',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Peso Tara'),
        ),
        migrations.AlterField(
            model_name='actividadagricola',
            name='cantidadTrabajada',
            field=models.DecimalField(decimal_places=2, max_digits=15, verbose_name='HA Trabajada'),
        ),
        migrations.AlterField(
            model_name='cierrezafradetalle',
            name='cantidadAcopioNeto',
            field=models.DecimalField(decimal_places=2, max_digits=15, verbose_name='KG Acopiado'),
        ),
        migrations.AlterField(
            model_name='cierrezafradetalle',
            name='cierreZafra',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.cierrezafra'),
        ),
        migrations.AlterField(
            model_name='compra',
            name='esCredito',
            field=models.BooleanField(default=True, verbose_name='Es Crédito?'),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='costoPactado',
            field=models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Precio Pactado'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='esCliente',
            field=models.BooleanField(default=False, help_text='La persona será tratada como un cliente', verbose_name='Es Cliente?'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='esEmpleado',
            field=models.BooleanField(default=False, help_text='La persona será tratada como un empleado de la empresa', verbose_name='Es Empleado?'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='esProveedor',
            field=models.BooleanField(default=False, help_text='La persona será tratada como un proveedor', verbose_name='Es Proveedor?'),
        ),
        migrations.AlterField(
            model_name='venta',
            name='esCredito',
            field=models.BooleanField(default=True, verbose_name='Es Crédito?'),
        ),
    ]
