# Generated by Django 3.1 on 2021-12-04 17:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_auto_20211203_2041'),
    ]

    operations = [
        migrations.CreateModel(
            name='Zafra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=200, verbose_name='Descripcion')),
                ('anho', models.IntegerField(max_length=4, verbose_name='anho')),
                ('kgEstimado', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Kg Estimado')),
                ('esZafrinha', models.BooleanField(verbose_name='es Zafriña?')),
                ('estaCerrado', models.BooleanField(default=False, verbose_name='está Cerrado?')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='inventory.item', verbose_name='Item')),
            ],
        ),
    ]
