# Generated by Django 3.1 on 2021-12-04 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_zafra'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zafra',
            name='anho',
            field=models.IntegerField(verbose_name='anho'),
        ),
    ]
