# Generated by Django 3.1 on 2021-12-04 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_auto_20211204_1446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zafra',
            name='kgEstimado',
            field=models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Kg Estimado'),
        ),
    ]
