# Generated by Django 3.1 on 2021-12-04 18:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_auto_20211204_1452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zafra',
            name='anho',
            field=models.IntegerField(verbose_name='Anho'),
        ),
        migrations.AlterField(
            model_name='zafra',
            name='esZafrinha',
            field=models.BooleanField(verbose_name='Es Zafriña?'),
        ),
        migrations.AlterField(
            model_name='zafra',
            name='estaCerrado',
            field=models.BooleanField(default=False, verbose_name='Está Cerrado?'),
        ),
        migrations.CreateModel(
            name='Lote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=200, verbose_name='Descripcion')),
                ('dimension', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Dimensión HA')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('finca', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='inventory.finca', verbose_name='Finca')),
                ('zafra', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='inventory.zafra', verbose_name='Zafra')),
            ],
        ),
    ]
