# Generated by Django 3.1 on 2021-12-05 18:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_auto_20211204_1506'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaquinariaAgricola',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=200, verbose_name='Descripcion')),
                ('esImplemento', models.BooleanField(verbose_name='Es Implemento?')),
                ('admiteImplemento', models.BooleanField(verbose_name='Admite Implento?')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Precio')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('tipoMaquinariaAgricola', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='inventory.tipomaquinariaagricola', verbose_name='Maquinaria Agrícola Tipo')),
            ],
        ),
    ]
