# Generated by Django 3.1 on 2021-12-05 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_maquinariaagricola'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banco',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=200, unique=True, verbose_name='Descripcion')),
            ],
        ),
        migrations.AlterField(
            model_name='maquinariaagricola',
            name='admiteImplemento',
            field=models.BooleanField(verbose_name='Admite Implemento?'),
        ),
    ]
