# Generated by Django 3.1 on 2021-12-05 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_auto_20211205_1522'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deposito',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=200, unique=True, verbose_name='Descripcion')),
                ('esPlantaAcopiadora', models.BooleanField(default=False, verbose_name='Es Planta Acopiadora?')),
            ],
        ),
    ]
