# Generated by Django 3.1 on 2021-12-06 12:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_deposito'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cuenta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=200, unique=True, verbose_name='Descripcion')),
                ('esBanco', models.BooleanField(default=False, verbose_name='Es Banco?')),
                ('nroCuenta', models.CharField(blank=True, max_length=200, null=True, verbose_name='Nro Cuenta')),
                ('banco', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='inventory.item', verbose_name='Banco')),
            ],
        ),
    ]
