# Generated by Django 3.1 on 2021-12-06 12:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_cuenta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuenta',
            name='banco',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='inventory.banco', verbose_name='Banco'),
        ),
    ]
