# Generated by Django 3.1 on 2021-12-06 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0013_departamento_distrito_localidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='localidad',
            name='descripcion',
            field=models.CharField(max_length=200, verbose_name='Descripcion'),
        ),
    ]
