# Generated by Django 3.1 on 2021-12-06 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0014_auto_20211206_1046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='distrito',
            name='descripcion',
            field=models.CharField(max_length=200, verbose_name='Descripcion'),
        ),
    ]
