# Generated by Django 3.1 on 2021-12-06 14:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0015_auto_20211206_1048'),
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razonSocial', models.CharField(max_length=200, verbose_name='Razon Social')),
                ('documento', models.CharField(max_length=40, verbose_name='Documento')),
                ('direccion', models.CharField(max_length=200, verbose_name='Direccion')),
                ('celular', models.CharField(blank=True, max_length=60, null=True, verbose_name='Celular / Telefono')),
                ('esCliente', models.BooleanField(default=False, verbose_name='Es Cliente?')),
                ('esProveedor', models.BooleanField(default=False, verbose_name='Es Proveedor?')),
                ('esEmpleado', models.BooleanField(default=False, verbose_name='Es Empleado?')),
                ('localidad', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='inventory.localidad', verbose_name='Localidad')),
                ('pais', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='inventory.pais', verbose_name='Pais')),
            ],
        ),
    ]
