# Generated by Django 3.1 on 2021-12-09 16:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0016_persona'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanActividadZafra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('observacion', models.CharField(blank=True, max_length=300, null=True)),
                ('zafra', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='inventory.zafra')),
            ],
        ),
        migrations.CreateModel(
            name='PlanActividadZafraDetalle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaActividad', models.DateField()),
                ('descripcion', models.CharField(blank=True, max_length=300, null=True)),
                ('costo', models.DecimalField(decimal_places=2, max_digits=15)),
                ('finca', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='inventory.finca')),
                ('planActividadZafra', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='inventory.planactividadzafra')),
                ('tipoActividadAgricola', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='inventory.tipoactividadagricola')),
            ],
        ),
    ]
