# Generated by Django 3.1 on 2021-12-09 22:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0017_planactividadzafra_planactividadzafradetalle'),
    ]

    operations = [
        migrations.CreateModel(
            name='Acopio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(verbose_name='Fecha')),
                ('comprobante', models.CharField(max_length=30, verbose_name='Comprobante')),
                ('pBruto', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Peso Bruto')),
                ('pTara', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Peso Tara')),
                ('pDescuento', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Peso Descuento')),
                ('pBonificacion', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Peso Bonificación')),
                ('esTransportadoraPropia', models.BooleanField(default=False, verbose_name='Es Transportadora Propia?')),
                ('esVigente', models.BooleanField(default=True, verbose_name='Vigente?')),
                ('observacion', models.CharField(blank=True, max_length=300, null=True, verbose_name='Observación')),
                ('camion', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='inventory.maquinariaagricola', verbose_name='Camión')),
                ('conductor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='inventory.persona', verbose_name='Conductor')),
                ('deposito', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='inventory.deposito', verbose_name='Zafra')),
                ('zafra', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='inventory.zafra', verbose_name='Zafra')),
            ],
        ),
        migrations.CreateModel(
            name='CalificacionAgricola',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=200, unique=True, verbose_name='Descripcion')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='planactividadzafra',
            name='fecha',
            field=models.DateField(verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='planactividadzafra',
            name='observacion',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Observación'),
        ),
        migrations.AlterField(
            model_name='planactividadzafra',
            name='zafra',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='inventory.zafra', verbose_name='Zafra'),
        ),
        migrations.AlterField(
            model_name='planactividadzafradetalle',
            name='costo',
            field=models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Costo Estimado'),
        ),
        migrations.AlterField(
            model_name='planactividadzafradetalle',
            name='descripcion',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='planactividadzafradetalle',
            name='fechaActividad',
            field=models.DateField(verbose_name='Fecha Act.'),
        ),
        migrations.AlterField(
            model_name='planactividadzafradetalle',
            name='finca',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='inventory.finca', verbose_name='Finca'),
        ),
        migrations.AlterField(
            model_name='planactividadzafradetalle',
            name='tipoActividadAgricola',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='inventory.tipoactividadagricola', verbose_name='Tipo Actividad Agrícola'),
        ),
        migrations.CreateModel(
            name='AcopioDetalle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('peso', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Peso')),
                ('acopio', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='inventory.acopio')),
                ('finca', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='inventory.finca', verbose_name='Finca')),
                ('lote', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='inventory.lote', verbose_name='Lote')),
            ],
        ),
        migrations.CreateModel(
            name='AcopioCalificacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grado', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Grado')),
                ('porcentaje', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Porcentaje')),
                ('peso', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Peso')),
                ('acopio', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='inventory.acopio')),
                ('calificaionAgricola', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='inventory.calificacionagricola')),
            ],
        ),
    ]
