# Generated by Django 3.1 on 2021-12-11 18:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0018_auto_20211209_1929'),
    ]

    operations = [
        migrations.CreateModel(
            name='PedidoCompra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaDocumento', models.DateField(verbose_name='Fecha Documento')),
                ('fechaVencimiento', models.DateField(verbose_name='Fecha Vencimiento')),
                ('esVigente', models.BooleanField(default=True, verbose_name='Vigente?')),
                ('observacion', models.CharField(blank=True, max_length=300, null=True, verbose_name='Observación')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='inventory.persona', verbose_name='Proveedor')),
            ],
        ),
        migrations.RenameField(
            model_name='acopiocalificacion',
            old_name='calificaionAgricola',
            new_name='calificacionAgricola',
        ),
        migrations.AlterField(
            model_name='acopio',
            name='deposito',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='inventory.deposito', verbose_name='Depósito'),
        ),
        migrations.CreateModel(
            name='PedidoCompraDetalle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Cantidad')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='inventory.item', verbose_name='Item')),
                ('pedidoCompra', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='inventory.pedidocompra')),
            ],
        ),
    ]
