# Generated by Django 3.1 on 2021-12-15 22:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0020_ordencompra_ordencompradetalle'),
    ]

    operations = [
        migrations.CreateModel(
            name='AperturaCaja',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observacion', models.CharField(blank=True, max_length=300, null=True, verbose_name='Observación')),
                ('fechaHoraRegistro', models.DateTimeField(auto_now_add=True)),
                ('estaCerrado', models.BooleanField(default=False, verbose_name='Esta Cerrado?')),
                ('montoInicio', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Monto Apertura')),
                ('fechaHoraCierre', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha Hora Cierre')),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='inventory.persona', verbose_name='Empleado')),
            ],
        ),
    ]
