# Generated by Django 3.1 on 2021-12-15 23:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0021_aperturacaja'),
    ]

    operations = [
        migrations.CreateModel(
            name='Arqueo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observacion', models.CharField(blank=True, max_length=300, null=True, verbose_name='Observación')),
                ('fechaHoraRegistro', models.DateTimeField(auto_now_add=True)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Monto A Retirar')),
                ('aperturaCaja', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='inventory.aperturacaja', verbose_name='Apertura Caja')),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='inventory.persona', verbose_name='Empleado')),
            ],
        ),
    ]
