# Generated by Django 3.1 on 2022-01-03 22:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0022_arqueo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaDocumento', models.DateField(verbose_name='Fecha Documento')),
                ('fechaHoraRegistro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha Hora Registro')),
                ('comprobante', models.CharField(max_length=15, verbose_name='Comprobante')),
                ('timbrado', models.CharField(max_length=8, verbose_name='Timbrado')),
                ('esCredito', models.CharField(max_length=8, verbose_name='Es Crédito?')),
                ('esVigente', models.BooleanField(default=True, verbose_name='Vigente?')),
                ('observacion', models.CharField(blank=True, max_length=300, null=True, verbose_name='Observación')),
                ('cuenta', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='inventory.cuenta', verbose_name='Cuenta')),
                ('deposito', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='inventory.deposito', verbose_name='Deposito')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='inventory.persona', verbose_name='Proveedor')),
            ],
        ),
        migrations.AlterField(
            model_name='aperturacaja',
            name='fechaHoraRegistro',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha Hora Registro'),
        ),
        migrations.AlterField(
            model_name='arqueo',
            name='fechaHoraRegistro',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha Hora Registro'),
        ),
        migrations.AlterField(
            model_name='arqueo',
            name='monto',
            field=models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Monto Retirado'),
        ),
        migrations.CreateModel(
            name='CompraDetalle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Cantidad')),
                ('costo', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Costo')),
                ('porcentajeImpuesto', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='% Impuesto')),
                ('compra', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='inventory.compra')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='inventory.item', verbose_name='Item')),
            ],
        ),
    ]
