# Generated by Django 3.1 on 2022-01-03 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0023_auto_20220103_1949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compra',
            name='esCredito',
            field=models.BooleanField(default=True, verbose_name='Es Crédito?'),
        ),
    ]
