# Generated by Django 3.1 on 2022-01-03 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0025_auto_20220103_1951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compra',
            name='esCredito',
            field=models.BooleanField(default=False, verbose_name='Es Crédito?'),
        ),
        migrations.AlterField(
            model_name='compra',
            name='esVigente',
            field=models.BooleanField(default=True, verbose_name='Vigente?'),
        ),
    ]
