# Generated by Django 3.1 on 2022-01-06 22:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0027_itemmovimiento'),
    ]

    operations = [
        migrations.CreateModel(
            name='AjusteStock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaDocumento', models.DateField(verbose_name='Fecha')),
                ('fechaHoraRegistro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha Hora Registro')),
                ('comprobante', models.CharField(max_length=15, verbose_name='Comprobante')),
                ('observacion', models.CharField(blank=True, max_length=300, null=True, verbose_name='Observación')),
                ('deposito', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='inventory.deposito', verbose_name='Deposito')),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='inventory.persona', verbose_name='Empleado')),
            ],
        ),
        migrations.CreateModel(
            name='AjusteStockDetalle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Cantidad')),
                ('ajusteStock', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='inventory.ajustestock')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='inventory.item', verbose_name='Item')),
            ],
        ),
    ]
