# Generated by Django 3.1 on 2022-01-17 22:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0028_ajustestock_ajustestockdetalle'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActividadAgricola',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaDocumento', models.DateField(verbose_name='Fecha')),
                ('fechaHoraRegistro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha Hora Registro')),
                ('comprobante', models.CharField(max_length=15, verbose_name='Comprobante')),
                ('observacion', models.CharField(blank=True, max_length=300, null=True, verbose_name='Observación')),
                ('esVigente', models.BooleanField(default=True, verbose_name='Vigente?')),
                ('esServicioContratado', models.BooleanField(default=False, verbose_name='Es servicio contratado?')),
                ('cantidadTrabajada', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Cantida HA Trabajada')),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='inventory.persona', verbose_name='Empleado')),
                ('finca', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='inventory.finca', verbose_name='Finca')),
                ('lote', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='inventory.lote', verbose_name='Lote')),
                ('tipoActividadAgricola', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='inventory.tipoactividadagricola', verbose_name='Tipo Actividad Agrícola')),
                ('zafra', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='inventory.zafra', verbose_name='Zafra')),
            ],
        ),
        migrations.AlterField(
            model_name='acopiocalificacion',
            name='calificacionAgricola',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='inventory.calificacionagricola', verbose_name='Calif. Agrícola'),
        ),
        migrations.CreateModel(
            name='ActividadAgricolaMaquinariaDetalle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('haTrabajada', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Ha Trabajada')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Precio')),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Cantidad')),
                ('actividadAgricola', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='inventory.actividadagricola')),
                ('maquinaria', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='inventory.maquinariaagricola', verbose_name='Maquinaria')),
            ],
        ),
        migrations.CreateModel(
            name='ActividadAgricolaItemDetalle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('haTrabajada', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Ha Trabajada')),
                ('costo', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Costo')),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Cantidad')),
                ('porcentajeImpuesto', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='% Impuesto')),
                ('dosis', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Dosis')),
                ('actividadAgricola', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='inventory.actividadagricola')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='inventory.item', verbose_name='Item')),
            ],
        ),
    ]
