# Generated by Django 3.1 on 2022-01-17 22:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0029_auto_20220117_1916'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actividadagricola',
            name='comprobante',
        ),
        migrations.AddField(
            model_name='actividadagricolaitemdetalle',
            name='deposito',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='inventory.deposito', verbose_name='Deposito'),
        ),
    ]
