# Generated by Django 3.1 on 2022-01-17 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0030_auto_20220117_1944'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actividadagricolaitemdetalle',
            name='haTrabajada',
        ),
        migrations.AlterField(
            model_name='actividadagricola',
            name='cantidadTrabajada',
            field=models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Cantidad HA Trabajada'),
        ),
    ]
