# Generated by Django 3.1 on 2022-01-17 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0031_auto_20220117_1951'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actividadagricolamaquinariadetalle',
            name='cantidad',
        ),
        migrations.AlterField(
            model_name='actividadagricolamaquinariadetalle',
            name='precio',
            field=models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Precio HA'),
        ),
    ]
