# Generated by Django 3.1 on 2022-01-18 22:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0032_auto_20220117_1953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actividadagricola',
            name='cantidadTrabajada',
            field=models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Cant HA Trabajada'),
        ),
        migrations.AlterField(
            model_name='actividadagricola',
            name='esServicioContratado',
            field=models.BooleanField(default=False, verbose_name='Es contratado?'),
        ),
        migrations.AlterField(
            model_name='actividadagricola',
            name='tipoActividadAgricola',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='inventory.tipoactividadagricola', verbose_name='Tipo Act. Agrícola'),
        ),
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('costoPactado', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Costo Pactado')),
                ('fecha', models.DateField(verbose_name='Fecha')),
                ('descripcion', models.CharField(max_length=300, verbose_name='Observación')),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='inventory.persona', verbose_name='Persona')),
                ('zafra', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='inventory.zafra', verbose_name='Zafra')),
            ],
        ),
    ]
