# Generated by Django 3.1 on 2022-01-28 23:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0036_notacreditoemitida_notacreditoemitidadetalle'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransferenciaCuenta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Monto a Transferir')),
                ('fecha', models.DateField(verbose_name='Fecha')),
                ('esVigente', models.BooleanField(default=True, verbose_name='Vigente?')),
                ('observacion', models.CharField(blank=True, max_length=300, null=True, verbose_name='Observación')),
                ('aperturaCaja', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='inventory.aperturacaja', verbose_name='Cuenta Entrada')),
                ('cuentaEntrada', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='entrada', to='inventory.cuenta', verbose_name='Cuenta Entrada')),
                ('cuentaSalida', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='salida', to='inventory.cuenta', verbose_name='Cuenta Salida')),
            ],
        ),
    ]
