# Generated by Django 3.1 on 2022-02-03 12:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0038_transferenciacuenta_comprobante'),
    ]

    operations = [
        migrations.CreateModel(
            name='CuotaVenta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaVencimiento', models.DateField(verbose_name='Fecha Vencimiento')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Monto')),
                ('saldo', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Saldo')),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='inventory.venta')),
            ],
        ),
        migrations.CreateModel(
            name='CuotaCompra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaVencimiento', models.DateField(verbose_name='Fecha Vencimiento')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Monto')),
                ('saldo', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Saldo')),
                ('compra', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='inventory.compra')),
            ],
        ),
    ]
