# Generated by Django 3.1 on 2022-02-05 14:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0039_cuotacompra_cuotaventa'),
    ]

    operations = [
        migrations.CreateModel(
            name='CierreZafra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(verbose_name='Fecha')),
                ('observacion', models.CharField(blank=True, max_length=300, null=True, verbose_name='Observación')),
                ('zafra', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='inventory.zafra', verbose_name='Zafra')),
            ],
        ),
        migrations.CreateModel(
            name='Cobro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaDocumento', models.DateField(verbose_name='Fecha')),
                ('fechaHoraRegistro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha Hora Registro')),
                ('observacion', models.CharField(blank=True, max_length=300, null=True, verbose_name='Observación')),
                ('esVigente', models.BooleanField(default=True, verbose_name='Vigente?')),
                ('montoASaldar', models.DecimalField(decimal_places=0, max_digits=15, verbose_name='Monto A Saldar')),
                ('comprobante', models.CharField(max_length=15, verbose_name='Comprobante')),
                ('aperturaCaja', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='inventory.aperturacaja', verbose_name='Apertura Caja')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='cliente', to='inventory.persona', verbose_name='Cliente')),
                ('cobrador', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='cobrador', to='inventory.persona', verbose_name='Cobrador')),
                ('cuenta', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='inventory.cuenta', verbose_name='Cuenta')),
            ],
        ),
        migrations.AlterField(
            model_name='cuotacompra',
            name='saldo',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Saldo'),
        ),
        migrations.AlterField(
            model_name='cuotaventa',
            name='saldo',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Saldo'),
        ),
        migrations.CreateModel(
            name='LiquidacionAgricolaDetalle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('haCultivada', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='HA Cultivada')),
                ('cantidadAcopioNeto', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Cant. Acopio')),
                ('rendimiento', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Rendimiento')),
                ('costoTotal', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Costo Total')),
                ('costoHA', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Costo HA')),
                ('costoUnit', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Costo Unit.')),
                ('cierreZafra', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='inventory.cierrezafra')),
                ('finca', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='inventory.finca', verbose_name='Finca')),
            ],
        ),
        migrations.CreateModel(
            name='LiquidacionAgricola',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaDocumento', models.DateField(verbose_name='Fecha')),
                ('fechaHoraRegistro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha Hora Registro')),
                ('observacion', models.CharField(blank=True, max_length=300, null=True, verbose_name='Observación')),
                ('esVigente', models.BooleanField(default=True, verbose_name='Vigente?')),
                ('precioUnitario', models.DecimalField(decimal_places=0, max_digits=15, verbose_name='Precio')),
                ('tipo', models.CharField(choices=[('ACOPIOS', 'LIQUIDACION DE ACOPIOS'), ('ACTIVIDADES AGRICOLAS', 'LIQUIDACION DE ACTIVIDADES AGRICOLAS')], max_length=50, verbose_name='Tipo Liquidación')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='inventory.persona', verbose_name='Proveedor')),
                ('zafra', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='inventory.zafra', verbose_name='Zafra')),
            ],
        ),
        migrations.CreateModel(
            name='CobroMedio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=15, verbose_name='N°')),
                ('comprobante', models.CharField(max_length=15, verbose_name='Comprobante')),
                ('monto', models.DecimalField(decimal_places=0, max_digits=15, verbose_name='Monto')),
                ('observacion', models.CharField(blank=True, max_length=300, null=True, verbose_name='Observación')),
                ('medioCobro', models.CharField(choices=[('CHEQUE DIF', 'CHEQUE DIFERIDO'), ('CHEQUE DIA', 'CHEQUE AL DIA'), ('EFECTIVO', 'EFECTIVO'), ('TRANSFERENCIA', 'TRANSFERENCIA BANCARIA')], max_length=50, verbose_name='Tipo Liquidación')),
                ('cobro', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='inventory.cobro')),
            ],
        ),
        migrations.CreateModel(
            name='CobroDetalle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cancelacion', models.DecimalField(decimal_places=0, max_digits=15, verbose_name='Cancelacion')),
                ('cobro', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='inventory.cobro')),
                ('cuotaCompra', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='inventory.cuotacompra', verbose_name='Cuota Compra')),
            ],
        ),
    ]
