# Generated by Django 3.1 on 2022-02-05 17:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0040_auto_20220205_1147'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cobrodetalle',
            name='cuotaCompra',
        ),
        migrations.AddField(
            model_name='cobrodetalle',
            name='cuotaVenta',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='inventory.cuotaventa', verbose_name='Cuota Venta'),
        ),
    ]
