# Generated by Django 3.1 on 2022-02-05 19:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0041_auto_20220205_1449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cobromedio',
            name='medioCobro',
            field=models.CharField(choices=[('CHEQUE DIF', 'CHEQUE DIFERIDO'), ('CHEQUE DIA', 'CHEQUE AL DIA'), ('EFECTIVO', 'EFECTIVO'), ('TRANSFERENCIA', 'TRANSFERENCIA BANCARIA')], max_length=50, verbose_name='Medio Cobro'),
        ),
        migrations.CreateModel(
            name='LiquidacionAgricolaDetalle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Cantidad')),
                ('secuenciaOrigen', models.IntegerField()),
                ('finca', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='inventory.finca', verbose_name='Finca')),
                ('liquidacionAgricola', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='inventory.liquidacionagricola')),
                ('lote', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='inventory.lote', verbose_name='Lote')),
            ],
        ),
    ]
