# Generated by Django 3.1 on 2022-02-05 19:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0042_auto_20220205_1602'),
    ]

    operations = [
        migrations.CreateModel(
            name='CierreZafraDetalle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('haCultivada', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='HA Cultivada')),
                ('cantidadAcopioNeto', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Cant. Acopio')),
                ('rendimiento', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Rendimiento')),
                ('costoTotal', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Costo Total')),
                ('costoHA', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Costo HA')),
                ('costoUnit', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Costo Unit.')),
                ('cierreZafra', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='inventory.cierrezafra')),
                ('finca', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='inventory.finca', verbose_name='Finca')),
            ],
        ),
    ]
