# Generated by Django 3.1 on 2022-02-06 18:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0044_notadebitorecibida_notadebitorecibidadetalle'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotaDebitoEmitida',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaDocumento', models.DateField(verbose_name='Fecha Documento')),
                ('fechaHoraRegistro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha Hora Registro')),
                ('comprobante', models.CharField(max_length=15, verbose_name='Comprobante')),
                ('timbrado', models.CharField(max_length=8, verbose_name='Timbrado')),
                ('esCredito', models.BooleanField(default=False, verbose_name='Es Crédito?')),
                ('esVigente', models.BooleanField(default=True, verbose_name='Vigente?')),
                ('observacion', models.CharField(blank=True, max_length=300, null=True, verbose_name='Observación')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='inventory.persona', verbose_name='Cliente')),
                ('cuenta', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='inventory.cuenta', verbose_name='Cuenta')),
                ('deposito', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='inventory.deposito', verbose_name='Deposito')),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='inventory.venta', verbose_name='Venta')),
            ],
        ),
        migrations.CreateModel(
            name='NotaDebitoEmitidaDetalle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Cantidad')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Costo/Descuento')),
                ('porcentajeImpuesto', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='% Impuesto')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='inventory.item', verbose_name='Item')),
                ('notaDebitoEmitida', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='inventory.notadebitoemitida')),
            ],
        ),
    ]
